data:
  mode: "pretrain"
  data: 
    sky-pile150B: "data/skypile/2020-40_*.jsonl"
    openwebtext: "data/openwebtext/openwebtext.jsonl"
  pad_to_max: False
  sequence_sample_mode: "none"
  concat_multiple_sequence: True
  num_sequences: 10
  seq_length: 600
  tokenizer_model_path: "configs/tokenizer_models/vocab_32k_gpt2_moe.model"
  split_by_shard: False
train:
  train_batch_size: 16
  num_training_steps: 1000000
  num_warmup_steps: 2000
  initializer_range: 1.0e-2
  lr: 2.0e-4
  ckpt:
  weight_decay: 1.0e-1
  train_num_workers_4_dataloader: 16
  gradient_accumulation_steps: 2
  prefetch_factor: 100
  train_and_eval: False
  gradient_checkpointing_enable: False
  use_lora: False
# global step
log_interval: 10
eval_interval: 100
save_interval: 1000
work_dir: "ckpt/vocab_32k_gpt2_moe"
project_name: "vocab_32k_gpt2_moe_Pretrain"
